version: '3'
services:
    web1:
        image: httpd
        container_name: test_httpd
        tty: true
        ports:
            - "8080:80"
        volumes:
            - "./htdocs:/usr/local/apache2/htdocs/"
