version: '3'
services:
    proxy:
        image: nginx
        container_name: nginx_reverse_proxy
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./reverse_proxy.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - web
    web:
        image: httpd
        container_name: backend_httpd_test
        tty: true
        ports:
            - "8080:80"
        volumes:
            - "./htdocs:/usr/local/apache2/htdocs"
